ingress:
  admin:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: cloudflare-velmios-dev
    hosts:
      - host: hydra-admin.stg.velmios.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: hydra-admin-tls
        hosts:
          - hydra-admin.stg.velmios.dev
  public:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: cloudflare-velmios-dev
    hosts:
      - host: hydra.stg.velmios.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: laelidona-tls
        hosts:
          - hydra.stg.velmios.dev

secret:
  enabled: false
  nameOverride: velmios-internal-hydra

hydra:
  automigration:
    enabled: true

  config:
    serve:
      public:
        cors:
          enabled: true
          allowed_origins:
            - "*"
    urls:
      self:
        public: https://hydra.stg.velmios.dev
        issuer: https://hydra.stg.velmios.dev
