global:
  storageClass: "openebs-replica"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-velmios-dev
  ingressClassName: nginx
  hostname: mailpit-stg.velmios.dev
  tls: true

persistence:
  enabled: true
