expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.stg.velmios.dev
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-velmios-dev
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    className: "nginx"
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: openebs-replica
      size: 10Gi
    jobservice:
      jobLog:
        storageClass: openebs-replica
    database:
      storageClass: openebs-replica
    redis:
      storageClass: openebs-replica
    trivy:
      storageClass: openebs-replica
    chartmuseum:
      storageClass: openebs-replica

externalURL: https://harbor.stg.velmios.dev

trivy:
  enabled: true
