apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velmios-customer-common
  namespace: argocd
spec:
  project: velmios
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velmios-customer
  sources:
    # Manifest
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/velmios/customer/common
      targetRevision: HEAD

