apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velmios-customer-kratos
  namespace: argocd
spec:
  project: velmios
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velmios-customer
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    # Manifest
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/velmios/customer/kratos
      targetRevision: HEAD
    # Helm Chart
    - repoURL: https://k8s.ory.sh/helm/charts
      chart: kratos
      targetRevision: 0.50.*
      helm:
        valueFiles:
          - $values/argocd/velmios/customer/kratos/values.yml
    # Values
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      targetRevision: HEAD
      ref: values

