apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    # Manifest
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/monitoring/loki
      targetRevision: HEAD
    # HelmChart
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.*"
      helm:
        releaseName: loki
        valueFiles:
          - $values/argocd/monitoring/loki/values.yml
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring-loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
