apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # Manifest
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/argocd
      targetRevision: HEAD
    # HelmChart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: "7.*"
      helm:
        releaseName: argocd
        valueFiles:
          - $values/argocd/argocd/values.yaml
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
