apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  sources:
    # Manifest
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/cloudflared
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflared
  syncPolicy:
    automated:
      selfHeal: true