apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/minio/manifest
      targetRevision: HEAD
    # - repoURL: https://operator.min.io
    #   chart: tenant
    #   targetRevision: 7.*
    #   helm:
    #     releaseName: minio-tenant
    #     namespace: minio
    #     valueFiles:
    #       - $values/argocd/minio/values.yaml
    # - repoURL: https://operator.min.io
    #   chart: minio-operator
    #   targetRevision: 4.*
    #   helm:
    #     releaseName: minio-operator
    #     namespace: minio
    #     valueFiles:
    #       - $values/argocd/minio/values.yaml
    # - repoURL: https://github.com/DeerHide/infra_git_ops.git
    #   targetRevision: HEAD
    #   ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated:
      selfHeal: true
