apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/DeerHide/infra_git_ops.git
      path: argocd/monitoring
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
