ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-velmios-dev
  hosts:
    - grafana-stg.velmios.dev
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana-stg.velmios.dev

persistence:
  enabled: true
  storageClassName: openebs-single-replica

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password
