apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velmios-env-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgAJ0NtgoHMJNGFCinFVZ2tk3bqUarEHTDmrTMana+ikt1VYhx26oIFAu8ZBhJ4R8nb/nz5JZh+tzp/aorYTnT2omihUAOTlcI0UtEDddKG/RNh5IDy4JlWQqrtDFJgXDVsxQj3J9rlPYMHxPA8BM6l2/XyyBApbIg0C7bqvd7xUR+LOI86GQAeldZaiJ/H4VcqYs1pM+rq9R07CuX8Ly63LEmxIm3lkZxTmIxkewitgeU7+BNzRYz1B99dqNdgm5N/jkLmCVJWmdUv7X8j1wdw5wiT3ymx+FLkHlS0JBK5BBP8+T4t0TxX7LBL97CueufoCYfjReCtkZUqi9MHfjL5zEwnKJdVK4obip8RknThw7Gq0WThopJqEmU17I7nMhM0nANNkrtfn5Sts/ngALGpKtm69sw0Oxskt/RCEu0iE4NoZDt6oRt3X5qy3fQWpnSHwSX+KwK4ws+UjT9TKXEx1H/DJBlQIPor8lys07dgkjLZWHEyXGX2PWvWudJs4WvNSJ/LtnymxWu4VLc1EuTMEV6wxwV5XyHQG9AiKF1PGaNoZPmdcb25qkkVdvP9XyHQKKwgz/inuMU3PfptFzvFi4Wb8oFS7aPpywEa5Icd/X8bgN/VpS27hgNW+Grre6CUMzPnjIwfnrfnUGWEgQHBPjiEdkS61cNGJNTujokgSvCHkgNttIgoCZNhVsQ780eOPl3ZOaPAblfd0oND24h0p1xx7kP4ee6pM9Q0XUqYtoxtJCEaAgVlkKHWt8ty3Ta3wngtXHz430XuOhx/rVcfR3/TJTs7/c5CJvUTm8gNAxM1ktTrQs7OOzSNfmbjF3SiOcRDb++luEYPa6LyVZyA=
  template:
    metadata:
      creationTimestamp: null
      name: velmios-env-configuration
      namespace: minio
---