apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velmios-internal-hydra-postgresql
  namespace: argocd
spec:
  project: velmios
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velmios-internal
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    # PostgreSQL
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 16.*
      helm:
        releaseName: velmios-internal-hydra-postgresql
        valuesObject:
          global:
            defaultStorageClass: openebs-replica
            postgresql:
              auth:
                enablePostgresUser: true
                database: hydra
                username: hydra
                existingSecret: velmios-internal-hydra-postgresql-secret
                adminPasswordKey: postgres-password 
                userPasswordKey: password
          architecture: standalone
          volumePermissions:
            enabled: true
          tls:
            enabled: false